require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TechnicalsController do

  # This should return the minimal set of attributes required to create a valid
  # Technical. As you add validations to Technical, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TechnicalsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all technicals as @technicals" do
      technical = Technical.create! valid_attributes
      get :index, {}, valid_session
      assigns(:technicals).should eq([technical])
    end
  end

  describe "GET show" do
    it "assigns the requested technical as @technical" do
      technical = Technical.create! valid_attributes
      get :show, {:id => technical.to_param}, valid_session
      assigns(:technical).should eq(technical)
    end
  end

  describe "GET new" do
    it "assigns a new technical as @technical" do
      get :new, {}, valid_session
      assigns(:technical).should be_a_new(Technical)
    end
  end

  describe "GET edit" do
    it "assigns the requested technical as @technical" do
      technical = Technical.create! valid_attributes
      get :edit, {:id => technical.to_param}, valid_session
      assigns(:technical).should eq(technical)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Technical" do
        expect {
          post :create, {:technical => valid_attributes}, valid_session
        }.to change(Technical, :count).by(1)
      end

      it "assigns a newly created technical as @technical" do
        post :create, {:technical => valid_attributes}, valid_session
        assigns(:technical).should be_a(Technical)
        assigns(:technical).should be_persisted
      end

      it "redirects to the created technical" do
        post :create, {:technical => valid_attributes}, valid_session
        response.should redirect_to(Technical.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved technical as @technical" do
        # Trigger the behavior that occurs when invalid params are submitted
        Technical.any_instance.stub(:save).and_return(false)
        post :create, {:technical => { "name" => "invalid value" }}, valid_session
        assigns(:technical).should be_a_new(Technical)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Technical.any_instance.stub(:save).and_return(false)
        post :create, {:technical => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested technical" do
        technical = Technical.create! valid_attributes
        # Assuming there are no other technicals in the database, this
        # specifies that the Technical created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Technical.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => technical.to_param, :technical => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested technical as @technical" do
        technical = Technical.create! valid_attributes
        put :update, {:id => technical.to_param, :technical => valid_attributes}, valid_session
        assigns(:technical).should eq(technical)
      end

      it "redirects to the technical" do
        technical = Technical.create! valid_attributes
        put :update, {:id => technical.to_param, :technical => valid_attributes}, valid_session
        response.should redirect_to(technical)
      end
    end

    describe "with invalid params" do
      it "assigns the technical as @technical" do
        technical = Technical.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Technical.any_instance.stub(:save).and_return(false)
        put :update, {:id => technical.to_param, :technical => { "name" => "invalid value" }}, valid_session
        assigns(:technical).should eq(technical)
      end

      it "re-renders the 'edit' template" do
        technical = Technical.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Technical.any_instance.stub(:save).and_return(false)
        put :update, {:id => technical.to_param, :technical => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested technical" do
      technical = Technical.create! valid_attributes
      expect {
        delete :destroy, {:id => technical.to_param}, valid_session
      }.to change(Technical, :count).by(-1)
    end

    it "redirects to the technicals list" do
      technical = Technical.create! valid_attributes
      delete :destroy, {:id => technical.to_param}, valid_session
      response.should redirect_to(technicals_url)
    end
  end

end
